# Generated by Django 4.2 on 2024-11-27 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookreservation", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Reservationinfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("firstname", models.CharField(max_length=100)),
                ("bookname", models.CharField(max_length=100)),
            ],
        ),
    ]
