# Generated by Django 4.2 on 2024-11-27 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookreservation", "0002_reservationinfo"),
    ]

    operations = [
        migrations.CreateModel(
            name="Reservationinformation",
            fields=[
                ("studentid", models.IntegerField()),
                ("firstname", models.CharField(max_length=100)),
                ("lastname", models.CharField(max_length=100)),
                ("bookid", models.IntegerField(primary_key=True, serialize=False)),
                ("bookname", models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name="Reservationinfo",
        ),
    ]
