# Generated by Django 4.2 on 2024-11-27 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bookreservation", "0003_reservationinformation_delete_reservationinfo"),
    ]

    operations = [
        migrations.RenameField(
            model_name="reservationinformation",
            old_name="bookid",
            new_name="book_id",
        ),
        migrations.RenameField(
            model_name="reservationinformation",
            old_name="bookname",
            new_name="book_name",
        ),
        migrations.RenameField(
            model_name="reservationinformation",
            old_name="firstname",
            new_name="first_name",
        ),
        migrations.RenameField(
            model_name="reservationinformation",
            old_name="lastname",
            new_name="last_name",
        ),
        migrations.RenameField(
            model_name="reservationinformation",
            old_name="studentid",
            new_name="student_id",
        ),
    ]
